name: "Check"

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: "read"

jobs:
  check:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8" # v6.0.1
      - name: "Install python"
        uses: "actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548" # v6.1.0
        with:
          python-version: "3.10"
      - name: "Install uv"
        uses: "astral-sh/setup-uv@1e862dfacbd1d6d858c55d9b792c756523627244" # v7.1.4
        with:
          version: "0.9.16"
      - name: "Install dependencies"
        run: "uv sync --locked"

      - name: "Format"
        run: "uv run ruff format --check"
      - name: "Lint"
        run: "uv run ruff check"
      - name: "Type check"
        run: "uv run mypy ."
      - name: "Test"
        run: "uv run python -m unittest"
